/*
 * Licensed to Elasticsearch under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.elasticsearch.common.rounding;

import org.elasticsearch.ElasticsearchException;
import org.elasticsearch.Version;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.io.stream.StreamOutput;
import org.elasticsearch.common.io.stream.Writeable;
import org.elasticsearch.common.unit.TimeValue;
import org.joda.time.DateTimeZone;
import org.joda.time.IllegalInstantException;

import java.io.IOException;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoField;
import java.time.temporal.ChronoUnit;
import java.time.temporal.IsoFields;
import java.time.temporal.TemporalField;
import java.time.temporal.TemporalUnit;
import java.time.zone.ZoneOffsetTransition;
import java.time.zone.ZoneRules;
import java.util.Objects;

/**
 * A strategy for rounding long values.
 */
public abstract class RoundingJavaTime implements Writeable {

    public static String format(long epochMillis) {
        return Instant.ofEpochMilli(epochMillis) + "/" + epochMillis;
    }

    public enum DateTimeUnit {
        WEEK_OF_WEEKYEAR(   (byte) 1, IsoFields.WEEK_OF_WEEK_BASED_YEAR),
        YEAR_OF_CENTURY(    (byte) 2, ChronoField.YEAR_OF_ERA),
        QUARTER_OF_YEAR(    (byte) 3, IsoFields.QUARTER_OF_YEAR),
        MONTH_OF_YEAR(      (byte) 4, ChronoField.MONTH_OF_YEAR),
        DAY_OF_MONTH(       (byte) 5, ChronoField.DAY_OF_MONTH),
        HOUR_OF_DAY(        (byte) 6, ChronoField.HOUR_OF_DAY),
        MINUTES_OF_HOUR(    (byte) 7, ChronoField.MINUTE_OF_HOUR),
        SECOND_OF_MINUTE(   (byte) 8, ChronoField.SECOND_OF_MINUTE);

        private final byte id;
        private final TemporalField field;

        DateTimeUnit(byte id, TemporalField field) {
            this.id = id;
            this.field = field;
        }

        public byte getId() {
            return id;
        }

        public TemporalField getField() {
            return field;
        }

        public static DateTimeUnit resolve(byte id) {
            switch (id) {
                case 1: return WEEK_OF_WEEKYEAR;
                case 2: return YEAR_OF_CENTURY;
                case 3: return QUARTER_OF_YEAR;
                case 4: return MONTH_OF_YEAR;
                case 5: return DAY_OF_MONTH;
                case 6: return HOUR_OF_DAY;
                case 7: return MINUTES_OF_HOUR;
                case 8: return SECOND_OF_MINUTE;
                default: throw new ElasticsearchException("Unknown date time unit id [" + id + "]");
            }
        }

    }

    public abstract byte id();

    /**
     * Rounds the given value.
     */
    public abstract long round(long value);

    /**
     * Given the rounded value (which was potentially generated by {@link #round(long)}, returns the next rounding value. For example, with
     * interval based rounding, if the interval is 3, {@code nextRoundValue(6) = 9 }.
     *
     * @param value The current rounding value
     * @return The next rounding value;
     */
    public abstract long nextRoundingValue(long value);

    @Override
    public abstract boolean equals(Object obj);

    @Override
    public abstract int hashCode();

    public static Builder builder(DateTimeUnit unit) {
        return new Builder(unit);
    }

    public static Builder builder(TimeValue interval) {
        return new Builder(interval);
    }

    public static class Builder {

        private final DateTimeUnit unit;
        private final long interval;

        private ZoneId timeZone = ZoneOffset.UTC;

        public Builder(DateTimeUnit unit) {
            this.unit = unit;
            this.interval = -1;
        }

        public Builder(TimeValue interval) {
            this.unit = null;
            if (interval.millis() < 1)
                throw new IllegalArgumentException("Zero or negative time interval not supported");
            this.interval = interval.millis();
        }

        public Builder timeZone(ZoneId timeZone) {
            if (timeZone == null) {
                throw new IllegalArgumentException("Setting null as timezone is not supported");
            }
            this.timeZone = timeZone;
            return this;
        }

        public RoundingJavaTime build() {
            RoundingJavaTime timeZoneRounding;
            if (unit != null) {
                timeZoneRounding = new TimeUnitRounding(unit, timeZone);
            } else {
                timeZoneRounding = new TimeIntervalRounding(interval, timeZone);
            }
            return timeZoneRounding;
        }
    }

    static class TimeUnitRounding extends RoundingJavaTime {

        static final byte ID = 1;

        private final DateTimeUnit unit;
        private final ZoneId timeZone;
        private final boolean unitRoundsToMidnight;


        TimeUnitRounding(DateTimeUnit unit, ZoneId timeZone) {
            this.unit = unit;
            this.unitRoundsToMidnight = this.unit.field.getBaseUnit().getDuration().toMillis() > 60L * 60L * 1000L;
            this.timeZone = timeZone;
        }

        TimeUnitRounding(StreamInput in) throws IOException {
            unit = DateTimeUnit.resolve(in.readByte());
            timeZone = ZoneId.of(in.readString());
            unitRoundsToMidnight = unit.getField().getBaseUnit().getDuration().toMillis() > 60L * 60L * 1000L;
            throw new IllegalArgumentException("not yet implemented");
        }

        @Override
        public byte id() {
            return ID;
        }

        /**
         * @return The latest timestamp T which is strictly before utcMillis
         * and such that timeZone.getOffset(T) != timeZone.getOffset(utcMillis).
         * If there is no such T, returns Long.MAX_VALUE.
         */
        // TODO this could just return an instant!
        private long previousTransition(final long utcMillis) {
            ZoneRules zoneRules = timeZone.getRules();
            Instant instant = Instant.ofEpochMilli(utcMillis);

            final int offsetAtInputTime = zoneRules.getOffset(instant).getTotalSeconds();
//            final int offsetAtInputTime = timeZone.getOffset(utcMillis);
            do {
                // Some timezones have transitions that do not change the offset, so we have to
                // repeatedly call previousTransition until a nontrivial transition is found.

                ZoneOffsetTransition transition = zoneRules.previousTransition(instant);
                Instant previousTransitionInstant = transition != null ? transition.getInstant() : instant;
                if (previousTransitionInstant.equals(instant)) {
                    // There are no earlier transitions
                    return Long.MAX_VALUE;
                }
                assert previousTransitionInstant.isBefore(instant); // Progress was made
                instant = previousTransitionInstant;
            } while (zoneRules.getOffset(instant).getTotalSeconds() == offsetAtInputTime);

            return instant.toEpochMilli();
        }

        private long truncateTo(TemporalUnit unit, long utcMillis) {
            ZonedDateTime zonedDateTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(utcMillis), ZoneOffset.UTC)
                .withZoneSameInstant(timeZone);
            // truncateTo() does not work with bigger units, so we have to do it ourselves
            if (unit.equals(ChronoUnit.YEARS)) {
                return zonedDateTime.withMonth(1).withDayOfMonth(1).withHour(0).withNano(0).withSecond(0).withMinute(0)
                    .toInstant().toEpochMilli();
            } else if (unit.equals(IsoFields.QUARTER_YEARS)) {
                int quarter = (int) IsoFields.QUARTER_OF_YEAR.getFrom(zonedDateTime);
                int month = (( quarter - 1 ) * 3) + 1;
                return zonedDateTime.withMonth(month).withDayOfMonth(1).withNano(0).withSecond(0).withMinute(0).withHour(0)
                    .toInstant().toEpochMilli();
            } else if (unit.equals(ChronoUnit.MONTHS)) {
                return zonedDateTime.withDayOfMonth(1).withNano(0).withSecond(0).withMinute(0).withHour(0).toInstant().toEpochMilli();
            } else if (unit.equals(ChronoUnit.DAYS)) {
                return zonedDateTime.withNano(0).withSecond(0).withMinute(0).withHour(0).toInstant().toEpochMilli();
            } else if (unit.equals(ChronoUnit.HOURS)) {
                return zonedDateTime.withNano(0).withSecond(0).withMinute(0).toInstant().toEpochMilli();
            } else if (unit.equals(ChronoUnit.MINUTES)) {
                return zonedDateTime.withNano(0).withSecond(0).toInstant().toEpochMilli();
            } else if (unit.equals(ChronoUnit.SECONDS)) {
                return zonedDateTime.withNano(0).toInstant().toEpochMilli();
            } else if (unit.equals(ChronoUnit.WEEKS)) {
                return zonedDateTime.with(ChronoField.DAY_OF_WEEK, 1).withNano(0).withSecond(0).withMinute(0).withHour(0)
                    .toInstant().toEpochMilli();
            }

            throw new IllegalArgumentException("NOT YET IMPLEMENTED for unit " + unit);
        }

        @Override
        public long round(long utcMillis) {
            // fast shortcut for UTC
            if (timeZone.getRules().isFixedOffset()) {
                return truncateTo(unit.field.getBaseUnit(), utcMillis);
            }

            // When rounding to hours we consider any local time of the form 'xx:00:00' as rounded, even though this gives duplicate
            // bucket names for the times when the clocks go back. Shorter units behave similarly. However, longer units round down to
            // midnight, and on the days where there are two midnights we would rather pick the earlier one, so that buckets are
            // uniquely identified by the date.
            if (unitRoundsToMidnight) {
                final long anyLocalStartOfDay = truncateTo(unit.field.getBaseUnit(), utcMillis);
//                logger.info("### java input [{}] output [{}]", Instant.ofEpochMilli(utcMillis), Instant.ofEpochMilli(anyLocalStartOfDay));

                // `anyLocalStartOfDay` is _supposed_ to be the Unix timestamp for the start of the day in question in the current time
                // zone.  Mostly this just means "midnight", which is fine, and on days with no local midnight it's the first time that
                // does occur on that day which is also ok. However, on days with >1 local midnight this is _one_ of the midnights, but
                // may not be the first. Check whether this is happening, and fix it if so.

                final long previousTransition = previousTransition(anyLocalStartOfDay);

                if (previousTransition == Long.MAX_VALUE) {
                    // No previous transitions, so there can't be another earlier local midnight.
                    return anyLocalStartOfDay;
                }

                final long currentOffset = timeZone.getRules().getOffset(Instant.ofEpochMilli(anyLocalStartOfDay)).getTotalSeconds();
                final long previousOffset = timeZone.getRules().getOffset(Instant.ofEpochMilli(previousTransition)).getTotalSeconds();
                assert currentOffset != previousOffset;

                // NB we only assume interference from one previous transition. It's theoretically possible to have two transitions in
                // quick succession, both of which have a midnight in them, but this doesn't appear to happen in the TZDB so (a) it's
                // pointless to implement and (b) it won't be tested. I recognise that this comment is tempting fate and will likely
                // cause this very situation to occur in the near future, and eagerly look forward to fixing this using a loop over
                // previous transitions when it happens.

                final long alsoLocalStartOfDay = anyLocalStartOfDay + currentOffset - previousOffset;
                // `alsoLocalStartOfDay` is the Unix timestamp for the start of the day in question if the previous offset were in
                // effect.

                if (alsoLocalStartOfDay <= previousTransition) {
                    // Therefore the previous offset _is_ in effect at `alsoLocalStartOfDay`, and it's earlier than anyLocalStartOfDay,
                    // so this is the answer to use.
                    return alsoLocalStartOfDay;
                } else {
                    // The previous offset is not in effect at `alsoLocalStartOfDay`, so the current offset must be.
                    return anyLocalStartOfDay;
                }

            } else {
                do {
                    long rounded = Instant.ofEpochMilli(utcMillis).truncatedTo(unit.field.getBaseUnit()).toEpochMilli();

                    // field.roundFloor() mostly works as long as the offset hasn't changed in [rounded, utcMillis], so look at where
                    // the offset most recently changed.

                    final long previousTransition = previousTransition(utcMillis);

                    if (previousTransition == Long.MAX_VALUE || previousTransition < rounded) {
                        // The offset did not change in [rounded, utcMillis], so roundFloor() worked as expected.
                        return rounded;
                    }

                    // The offset _did_ change in [rounded, utcMillis]. Put differently, this means that none of the times in
                    // [previousTransition+1, utcMillis] were rounded, so the rounded time must be <= previousTransition.  This means
                    // it's sufficient to try and round previousTransition down.
                    assert previousTransition < utcMillis;
                    utcMillis = previousTransition;
                } while (true);
            }
        }

        @Override
        public long nextRoundingValue(long utcMillis) {
            final long floor = round(utcMillis);
            // add one unit and round to get to next rounded value
            long next;
            // TODO this can be reduced again thx to the changes in truncateTo()
            if (unit.field.getBaseUnit().equals(ChronoUnit.MONTHS)) {
                long beforeRoundMillis = ZonedDateTime.ofInstant(Instant.ofEpochMilli(floor), ZoneOffset.UTC)
                    .withZoneSameInstant(timeZone).plusMonths(1).toInstant().toEpochMilli();
                next = round(beforeRoundMillis);
            } else if (unit.field.getBaseUnit().equals(ChronoUnit.YEARS)) {
                long beforeRoundMillis = ZonedDateTime.ofInstant(Instant.ofEpochMilli(floor), timeZone)
                    .plusYears(1).toInstant().toEpochMilli();
                next = round(beforeRoundMillis);
            } else if (unit.field.getBaseUnit().equals(IsoFields.QUARTER_YEARS)) {
                long beforeRoundMillis = ZonedDateTime.ofInstant(Instant.ofEpochMilli(floor), timeZone)
                    .plus(1, IsoFields.QUARTER_YEARS).toInstant().toEpochMilli();
                next = round(beforeRoundMillis);
            } else {
                next = round(floor + unit.field.getBaseUnit().getDuration().toMillis());
            }
            if (next == floor) {
                // in rare case we need to add more than one unit
                if (unit.field.getBaseUnit().equals(ChronoUnit.MONTHS)) {
                    next = round(ZonedDateTime.ofInstant(Instant.ofEpochMilli(floor), ZoneOffset.UTC)
                        .withZoneSameInstant(timeZone).plusMonths(1).toInstant().toEpochMilli());
                } else if (unit.field.getBaseUnit().equals(ChronoUnit.YEARS)) {
                    long beforeRoundMillis =
                        ZonedDateTime.ofInstant(Instant.ofEpochMilli(floor), timeZone).plusYears(1).toInstant().toEpochMilli();
                    next = round(beforeRoundMillis);
                } else if (unit.field.getBaseUnit().equals(IsoFields.QUARTER_YEARS)) {
                    long beforeRoundMillis = ZonedDateTime.ofInstant(Instant.ofEpochMilli(floor), timeZone)
                        .plus(1, IsoFields.QUARTER_YEARS).toInstant().toEpochMilli();
                    next = round(beforeRoundMillis);
                } else {
                    next = round(floor + unit.field.getBaseUnit().getDuration().toMillis() * 2);
                }
            }
            return next;
        }

        @Override
        public void writeTo(StreamOutput out) throws IOException {
            if (out.getVersion().onOrAfter(Version.V_7_0_0_alpha1)) {
                out.writeVInt(unit.ordinal());
            }
            out.writeString(timeZone.getId());
        }

        @Override
        public int hashCode() {
            return Objects.hash(unit, timeZone);
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            TimeUnitRounding other = (TimeUnitRounding) obj;
            return Objects.equals(unit, other.unit) && Objects.equals(timeZone, other.timeZone);
        }

        @Override
        public String toString() {
            return "[" + timeZone + "][" + unit + "]";
        }
    }

    static class TimeIntervalRounding extends RoundingJavaTime {

        static final byte ID = 2;

        private final long interval;
        private final ZoneId timeZone;

        TimeIntervalRounding(long interval, ZoneId timeZone) {
            if (interval < 1)
                throw new IllegalArgumentException("Zero or negative time interval not supported");
            this.interval = interval;
            this.timeZone = timeZone;
        }

        TimeIntervalRounding(StreamInput in) throws IOException {
            interval = in.readVLong();
            timeZone = ZoneId.of(in.readString());
        }

        @Override
        public byte id() {
            return ID;
        }

        @Override
        public long round(final long utcMillis) {
            final Instant utcInstant = Instant.ofEpochMilli(utcMillis);
            int offsetSeconds = timeZone.getRules().getOffset(utcInstant).getTotalSeconds();
            long timeLocal = utcMillis + (offsetSeconds * 1000);

            final long rounded = roundKey(timeLocal, interval) * interval;
            long roundedUTC;
            if (isInDSTGap(rounded) == false) {
                int offsetOriginal = timeZone.getRules().getOffset(utcInstant).getTotalSeconds();
                long instantUtc = rounded - (offsetOriginal * 1000);
                int offsetLocalFromOriginal = timeZone.getRules().getOffset(Instant.ofEpochMilli(instantUtc)).getTotalSeconds();
                if (offsetLocalFromOriginal == offsetOriginal) {
                    roundedUTC = instantUtc;
                } else {
                    int offsetLocal = timeZone.getRules().getOffset(Instant.ofEpochMilli(rounded)).getTotalSeconds();
                    int offset = timeZone.getRules().getOffset(Instant.ofEpochMilli(rounded - (offsetLocal * 1000))).getTotalSeconds();
                    if (offsetLocal != offset) {
                        long nextLocal = timeZone.getRules()
                            .nextTransition(Instant.ofEpochMilli(rounded - (offsetLocal * 1000))).getInstant().toEpochMilli();
                        if (nextLocal == (rounded - (offsetLocal * 1000))) {
                            nextLocal = Long.MAX_VALUE;
                        }
                        long nextAdjusted = timeZone.getRules()
                            .nextTransition(Instant.ofEpochMilli(rounded - (offset * 1000))).getInstant().toEpochMilli();
                        if (nextAdjusted == (rounded - (offset * 1000))) {
                            nextAdjusted = Long.MAX_VALUE;
                        }
                        if (nextAdjusted != nextLocal) {
                            offset = offsetLocal;
                        }
                    }
                    roundedUTC = rounded - (offset * 1000);
                }
                // check if we crossed DST transition, in this case we want the
                // last rounded value before the transition

                ZoneOffsetTransition offsetTransition = timeZone.getRules().previousTransition(Instant.ofEpochMilli(utcMillis+1));
                if (offsetTransition != null) {
                    long transition = offsetTransition.getInstant().toEpochMilli() - 1;
                    if (transition != utcMillis && transition > roundedUTC) {
                            roundedUTC = round(transition);
                    }
                }
            } else {
                /*
                 * Edge case where the rounded local time is illegal and landed
                 * in a DST gap. In this case, we choose 1ms tick after the
                 * transition date. We don't want the transition date itself
                 * because those dates, when rounded themselves, fall into the
                 * previous interval. This would violate the invariant that the
                 * rounding operation should be idempotent.
                 */
                ZoneOffsetTransition transition = timeZone.getRules().previousTransition(utcInstant);
                if (transition != null) {
                    long previousTransition = transition.getInstant().toEpochMilli();
                    // if the previous transition is older than what we rounded to, we cannot use it as we would go too far in the past
                    if (previousTransition < rounded) {
                        roundedUTC = utcMillis;
                    } else {
                        roundedUTC = previousTransition + 1;
                    }
                } else {
                    roundedUTC = utcMillis;
                }
            }
            return roundedUTC;
        }

        private static long roundKey(long value, long interval) {
            if (value < 0) {
                return (value - interval + 1) / interval;
            } else {
                return value / interval;
            }
        }

        /**
         * Determine whether the local instant is a valid instant in the given
         * time zone. The logic for this is taken from
         * {@link DateTimeZone#convertLocalToUTC(long, boolean)} for the
         * `strict` mode case, but instead of throwing an
         * {@link IllegalInstantException}, which is costly, we want to return a
         * flag indicating that the value is illegal in that time zone.
         */
        private boolean isInDSTGap(long instantLocal) {
            if (timeZone.getRules().isFixedOffset()) {
                return false;
            }

            // get the offset at instantLocal (first estimate)
            int offsetLocal = timeZone.getRules().getOffset(Instant.ofEpochMilli(instantLocal)).getTotalSeconds() * 1000;
            // adjust instantLocal using the estimate and recalc the offset
            int offset = timeZone.getRules().getOffset(Instant.ofEpochMilli(instantLocal - offsetLocal)).getTotalSeconds() * 1000;
            // if the offsets differ, we must be near a DST boundary
            if (offsetLocal != offset) {
                // determine if we are in the DST gap
                long nextLocal = Long.MIN_VALUE;
                ZoneOffsetTransition nextLocalTransition = timeZone.getRules()
                    .nextTransition(Instant.ofEpochMilli(instantLocal - offsetLocal + 1));
                if (nextLocalTransition != null) {
                    nextLocal = nextLocalTransition.getInstant().toEpochMilli();
                    if (nextLocal == (instantLocal - offsetLocal)) {
                        nextLocal = Long.MAX_VALUE;
                    }
                }
                long nextAdjusted = Long.MIN_VALUE;
                ZoneOffsetTransition zoneOffsetTransition = timeZone.getRules()
                    .nextTransition(Instant.ofEpochMilli(instantLocal - offset + 1));
                if (zoneOffsetTransition != null) {
                    nextAdjusted = zoneOffsetTransition.getInstant().toEpochMilli();
                    if (zoneOffsetTransition == null || nextAdjusted == (instantLocal - offset)) {
                        nextAdjusted = Long.MAX_VALUE;
                    }
                }
                if (nextLocal != nextAdjusted) {
                    // we are in the DST gap
                    return true;
                }
            }
            return false;
        }

        @Override
        public long nextRoundingValue(long time) {
            int offsetSeconds = timeZone.getRules().getOffset(Instant.ofEpochMilli(time)).getTotalSeconds();
            return ZonedDateTime.ofInstant(Instant.ofEpochMilli(time), ZoneOffset.UTC)
                .plusSeconds(offsetSeconds)
                .plusNanos(interval * 1_000_000)
                .withZoneSameLocal(timeZone)
                .toInstant().toEpochMilli();
        }

        @Override
        public void writeTo(StreamOutput out) throws IOException {
            out.writeVLong(interval);
            out.writeString(timeZone.getId());
        }

        @Override
        public int hashCode() {
            return Objects.hash(interval, timeZone);
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            TimeIntervalRounding other = (TimeIntervalRounding) obj;
            return Objects.equals(interval, other.interval) && Objects.equals(timeZone, other.timeZone);
        }
    }

    public static class Streams {

        public static void write(RoundingJavaTime rounding, StreamOutput out) throws IOException {
            out.writeByte(rounding.id());
            rounding.writeTo(out);
        }

        public static RoundingJavaTime read(StreamInput in) throws IOException {
            RoundingJavaTime rounding = null;
            byte id = in.readByte();
            switch (id) {
                case RoundingJavaTime.TimeUnitRounding.ID:
                    rounding = new RoundingJavaTime.TimeUnitRounding(in);
                    break;
                case RoundingJavaTime.TimeIntervalRounding.ID:
                    rounding = new RoundingJavaTime.TimeIntervalRounding(in);
                    break;
                default:
                    throw new ElasticsearchException("unknown rounding id [" + id + "]");
            }
            return rounding;
        }

    }

}
